[package]
name = "hexdiff"
version = "0.1.1"
authors = ["Robby Madruga <robbymadruga@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 3
lto = true

[dependencies]
ihex = "3.0.0"
structopt = "0.3.21"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
itertools = "0.10.1"